import { AuthConfig } from './auth/AuthConfig';
import { JWTManager } from './auth/JWTManager';
import { BaseController } from './controllers/BaseController';
import { DbConfig } from './database/db.config';
import { DBConnector } from './database/DBConnector';
import { BaseDTO } from './dto/baseDTO';
import { DataDTO } from './dto/dataDTO';
import { IdDTO } from './dto/IdDTO';
import { AuthenticationTokenMissingException } from './exceptions/AuthenticationTokenMissingException';
import { DBConnectionException } from './exceptions/DBConnectionException';
import { HttpException } from './exceptions/HttpException';
import { InvalidHandlerException } from './exceptions/InvalidHandlerException';
import { InvalidParamsException } from './exceptions/InvalidParamsException';
import { PageNotFoundException } from './exceptions/PageNotFoundException';
import { StandardException } from './exceptions/StandardException';
import { TimeoutException } from './exceptions/TimeoutException';
import { validationDataMiddleware, validationMiddleware } from './middlewares/validationMiddleware';
import { BaseModel } from './models/base.model';
import { CustomRoute } from './models/CustomRoute';
import { BaseApp } from './BaseApp';
import { Config } from './Config';
import { BasePresenter } from './presenters/BasePresenter';
import { BaseResponse } from './responses/BaseResponse';
import { CommonEndPoints } from './utils/CommonEndPoints';
import { validateEnv } from './utils/validateEnv';
declare const _default: {
    AuthConfig: typeof AuthConfig;
    JWTManager: typeof JWTManager;
    BaseController: typeof BaseController;
    DbConfig: typeof DbConfig;
    DBConnector: typeof DBConnector;
    validationMiddleware: typeof validationMiddleware;
    validationDataMiddleware: typeof validationDataMiddleware;
    BaseDTO: typeof BaseDTO;
    DataDTO: typeof DataDTO;
    IdDTO: typeof IdDTO;
    AuthenticationTokenMissingException: typeof AuthenticationTokenMissingException;
    DBConnectionException: typeof DBConnectionException;
    HttpException: typeof HttpException;
    InvalidHandlerException: typeof InvalidHandlerException;
    InvalidParamsException: typeof InvalidParamsException;
    PageNotFoundException: typeof PageNotFoundException;
    StandardException: typeof StandardException;
    TimeoutException: typeof TimeoutException;
    BaseModel: typeof BaseModel;
    CustomRoute: typeof CustomRoute;
    BaseResponse: typeof BaseResponse;
    BasePresenter: typeof BasePresenter;
    CommonEndPoints: typeof CommonEndPoints;
    validateEnv: typeof validateEnv;
    BaseApp: typeof BaseApp;
    Config: typeof Config;
};
export default _default;
